title: Clark Fitzgerald
description: >- # this means to ignore newlines until "baseurl:"
    Data science resources by Professor Clark Fitzgerald, Mathematics and Statistics Department, CSU Sacramento.
    Course materials, technology and software tutorials, case studies, and miscellaneous writing.
baseurl: "/fitzgerald"
url: "http://webpages.csus.edu"
twitter_username: clarkfitzg
github_username:  clarkfitzg

theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed

exclude:
    - makefile

include:
    - _pages

defaults:
  -
    scope:
        path: ""
        type: posts
    values:
        permalink: :title
        layout: single
        author_profile: true
        read_time: true
        comments: true
        share: true
        related: true
  -
    scope:
        path: "_pages"
        type: pages
    values:
        permalink: :title
        layout: single
        read_time: true
