title: Clark Fitzgerald
description: >- # this means to ignore newlines until "baseurl:"
    Web pages by Professor Clark Fitzgerald, Mathematics and Statistics Department, CSU Sacramento.
    Course materials, data science and software tutorials, and miscellaneous writing.
baseurl: "/fitzgerald"
url: "http://webpages.csus.edu"
twitter_username: clarkfitzg
github_username:  clarkfitzg

theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed

defaults:
    - scope:
        path: ""
        type: posts
      values:
        permalink: :title
        layout: single
        author_profile: true
        read_time: true
        comments: true
        share: true
        related: true
    - scope:
        path: ""
        type: pages
      values:
        permalink: :title
        layout: single
        read_time: true

include: 
    - _pages

exclude:
    - makefile
